language: python

python:
  - "3.5"

services:
  - docker # default is docker 1.8.2 and docker-compose 1.4.2 (as of Oct. 2016)

install: # prepare mySQL database
  - docker pull mysql:5.7.14
  - mkdir db
  - >
    docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS'
    -v `pwd`/db:/var/lib/mysql  mysql:5.7.14
  - sleep 10 # need to give time for mysql to start
  - >
    docker run -it --name mysql-cmd --rm --link mysql:db mysql:5.7.14
    mysql -uroot -p'$3cureUS' -h db -v -e
    "CREATE DATABASE cs4501 CHARACTER SET utf8;
    CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';
    GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"

before_script:
  - docker-compose up -d
 # - apt-get google-chrome-stable
  - docker ps -a
  - docker start talentx_models_1
#
script:
  - docker exec -it talentx_models_1 bash -c "python manage.py test"
  - pip install selenium
  # - pip install chromedriver
  # - cd /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/
  # - ls chromedriver
  - python front_end_test.py 
after_script:
  - docker-compose stop
  - docker stop mysql
  - docker rm `docker ps -a -q`
  - docker rmi `docker images -q`
  - sudo rm -rf db